import "@/app/globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import Header from "@/app/components/Header";
import { cn } from "@/app/utils/tailwind";
import { getDictionary } from "./dictionaries";
import { Locale } from "@/middleware";

const montserrat = Montserrat({ subsets: ["latin"] });
const firaGo = localFont({
  src: [
    {
      path: "./fonts/FiraGO/FiraGO-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/FiraGO/FiraGO-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/FiraGO/FiraGO-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/FiraGO/FiraGO-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/FiraGO/FiraGO-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const dict = await getDictionary(lang);
  return (
    <html lang={lang}>
      <body
        className={cn(
          "flex flex-col tracking-wider text-slate-300 sm:h-screen",
          { [montserrat.className]: lang === "en" },
          { [firaGo.className]: lang === "ge" },
        )}
      >
        <Header navDict={dict["navigation"]} />
        <div className="flex sm:basis-full">{children}</div>
      </body>
    </html>
  );
}
